### ISSUE TITLE
GUI Content and Appearance

### ISSUE THREAD

**Issue by AlanHam42** [Jscott44/RTEP5-the-raspberry-jam#1]
Mock up ideas for the GUI and what the user will actually be able to affect

**Comment by AlanHam42** [comment]
Branch has been created and development began locally.
The branch will be updated asap.

**Comment by AlanHam42** [comment]
Started development of Qt using the QtCreator IDE. This IDE will provide us with Header files, source files, html UI files as well as (if needed) a makefile.

**Comment by theOriginalMC** [comment]
Gui has been added to the rest of the program
