### ISSUE TITLE
GUI waveform display

### ISSUE THREAD

**Issue by AlanHam42** [Jscott44/RTEP5-the-raspberry-jam#13]
We wish to display a waveform that will apply effects (from Adi) using outputs from the output class created by the QTabWidget.

**Comment by AlanHam42** [comment]
Having some issues including the QCustomPlot library, the .h file is not included. This is an issue with the Cmake file that Alan will work on and then the plot can be added based on inputs from tabs.

**Comment by theOriginalMC** [comment]
QCustomPlot library is huge, and nigh impossible to use.
