### ISSUE TITLE
QTabWidget Current Index -> Effects Manager pointer relation

### ISSUE THREAD

**Issue by AlanHam42** [Jscott44/RTEP5-the-raspberry-jam#16]
The user can only affect the current index of tabs.
The EM returns a pointer for each new tab.
Each pointer needs to be stored in the same order as the tabs, and destroyed with the tabs.
The current index can then refer to the correct pointer, which will return values to the EM.

**Comment by theOriginalMC** [comment]
GUI now receives a pointer and sends variables to the Effects Manager
