### ISSUE TITLE
Driver for capture from generic PCM device

### ISSUE THREAD

**Issue by Jscott44** [Jscott44/RTEP5-the-raspberry-jam#3]
Basic functionality to recognise and then read from PCM device

**Comment by iamdario** [comment]
Created _audio_driver_dev_ branch for development to begin.

**Comment by Jscott44** [comment]
Created branch for specific capture development

**Comment by Jscott44** [comment]
Created basic framework for a generic device, waiting for finalised development of hardware platform in order to properly test interface with RPI.

**Comment by iamdario** [comment]
Has been implemented in the branch 'capture-from-generic-pcm-device'. Need to now merge effects manager to begin testing.

**Comment by iamdario** [comment]
Has been achieved and merged back into 'audio_driver_dev' branch in pull request #58 .
