### ISSUE TITLE
Driver for playback to generic PCM device

### ISSUE THREAD

**Issue by Jscott44** [Jscott44/RTEP5-the-raspberry-jam#4]
Functionality to write to a PCM device

**Comment by iamdario** [comment]
Created _audio_driver_dev_ branch for development to begin.

**Comment by Jscott44** [comment]
Waiting for hardware platform to be finished.

**Comment by Jscott44** [comment]
Added parent class that will define basic functions and configure settings. Capture and playback will be children of this class, settings are shared as much as possible and functions will be implemented differently where necessary.

**Comment by iamdario** [comment]
Has been implemented in the branch 'capture-from-generic-pcm-device'. Need to now merge effects manager to begin testing.

**Comment by iamdario** [comment]
Has been achieved and merged back into 'audio_driver_dev' branch in pull request #58 .
