### ISSUE TITLE
Effects cannot be simultaneously removed without program crashing

### ISSUE THREAD

**Issue by Jscott44** [Jscott44/RTEP5-the-raspberry-jam#87]
Need some sort of delay between remove effect calls

**Comment by Jscott44** [comment]
Might be to do with the GUI altering effects while em is processing

**Comment by iamdario** [comment]
After altering the GUI callbacks to ensure they do not alter, delete or add effects while they are being used by the program, the issue was resolved. Therefore fixed code has been merged into Development.
