### ISSUE TITLE
Button for enabling/disabling effect proccessing 

### ISSUE THREAD

**Issue by iamdario** [Jscott44/RTEP5-the-raspberry-jam#94]
A button will be required to enable/disable the effects from processing the incoming buffers. This button will interact with the rest of the code using a callback from a class responsible for waiting for an interrupt from a GPIO pin.

**Comment by Jscott44** [comment]
Moving to a hybrid system that can use a hardware button or a purely digital button.

**Comment by AlanHam42** [comment]
Button has been implemented in GUI.
